[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
chain_id = 42161
auto_detect_solc = false
solc_version = "0.8.16"
evm_version = "london"
via_ir = true
use_literal_content = true
optimizer = true
optimizer_runs = 200
libraries = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
